{% set name = "shrinkwrap" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jonathonl/shrinkwrap/archive/v{{ version }}.tar.gz
  sha256: 833e85bdc41e7bf82a57f0fb52958795fb089f691981d2e3a2b68eee17128082

build:
  skip: True  # [win]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - xz
    - zstd
    - zlib
  host:
    - xz
    - zlib
    - zstd

test:
  commands:
    - test -f $PREFIX/include/shrinkwrap/istream.hpp  # [not win]
    - test -f $PREFIX/include/shrinkwrap/stdio.hpp  # [not win]
    - test -f $PREFIX/include/shrinkwrap/gz.hpp  # [not win]
    - test -f $PREFIX/include/shrinkwrap/zstd.hpp  # [not win]
    - test -f $PREFIX/include/shrinkwrap/xz.hpp  # [not win]
    - test -f $PREFIX/share/shrinkwrap/shrinkwrap-config.cmake  # [not win]
    - test -f $PREFIX/share/shrinkwrap/shrinkwrap-config-version.cmake  # [not win]

about:
  home: https://github.com/jonathonl/shrinkwrap
  license: MIT
  license_file: LICENSE
  summary: A std::streambuf wrapper for compression formats.
  dev_url: https://github.com/jonathonl/shrinkwrap

extra:
  recipe-maintainers:
    - matuskosut
    - jonathonl
